name: dagim_portfolio_app
description: "Multi-section mobile portfolio inspired by dagim-portfolio web experience."
version: 1.0.0+1
environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.5
  smooth_page_indicator: ^1.1.0
  flutter_animate: ^4.4.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/Generated Image October 21, 2025 - 11_33PM.png"
  web:
    generate: true
    image_path: "assets/images/Generated Image October 21, 2025 - 11_33PM.png"
  linux:
    generate: true
    image_path: "assets/images/Generated Image October 21, 2025 - 11_33PM.png"
  macos:
    generate: true
    image_path: "assets/images/Generated Image October 21, 2025 - 11_33PM.png"
  windows:
    generate: true
    image_path: "assets/images/Generated Image October 21, 2025 - 11_33PM.png"
