name: Deploy Flutter Web

on:
  push:
    branches: [master]
    paths:
      - 'flutter_app/**'
      - '.github/workflows/flutter-web-pages.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Enable Flutter web support
        run: flutter config --enable-web

      - name: Get Flutter dependencies
        run: flutter pub get
        working-directory: flutter_app

      - name: Build Flutter web app
        run: flutter build web --release --base-href /dagim-portfolio/
        working-directory: flutter_app

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: flutter_app/build/web
